branch-defaults:
  default:
    environment: siarhei-karukhin-bff-api-dev
    group_suffix: null
global:
  application_name: siarhei-karukhin-bff-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: rss
  repository: null
  sc: null
  workspace_type: Application
